name: npm-install
description: Install Node, npm and dependencies
runs:
  using: "composite"
  steps:
    - name: Setup Turbo Cache
      uses: dtinth/setup-github-actions-caching-for-turbo@v1
      with:
        cache-prefix: tidymate_
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: 20
    - name: Get npm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(npm list -g | head -1)" >> $GITHUB_ENV
    - uses: actions/cache@v3
      name: Setup npm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-npm-store-${{ hashFiles('**/package-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-npm-store-
    - name: Install dependencies
      run: npm ci
      shell: bash