services:
  tidymate:
    container_name: tidymate
    image: tidymate:dev
    restart: always
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
    ports:
      - 3000:3000
    environment:
      FLASK_SECRET_KEY: "your_secret_key"
      LOG_DEBUG: True
