services:
  tidymate:
    container_name: tidymate
    image: tidymate:latest
    restart: always
    volumes:
      - ../data:/app/data
    ports:
      - 3000:3000
    environment:
      FLASK_SECRET_KEY: "your_secret_key"
      BASE_URL: "http://localhost:3000"
