version: '3.7'

name: 'tidymate'

services:
   tidymate-dev:
      image: tidymate-dev:0.1
      build: .
      container_name: tidymate-dev
      hostname: tidymate-dev.local
      working_dir: /work
      ports:
         - "3000:3000"
      volumes:
         - ..:/work
      command: bash -c "/work/.devcontainer/init.sh && sleep infinity"
      networks:
         tidymate:
networks:
   tidymate:
