"""Add href to notification

Revision ID: 3f085694b523
Revises: 5a93e0a44d99
Create Date: 2025-07-13 19:58:21.727388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f085694b523'
down_revision = '5a93e0a44d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'href',
                sa.String(
                    length=255),
                nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('href')

    # ### end Alembic commands ###
