"""empty message

Revision ID: 518f398b1bf5
Revises: 73b0a9c7bc69
Create Date: 2025-08-10 13:37:24.939416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518f398b1bf5'
down_revision = '73b0a9c7bc69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'notification_type',
                sa.Enum(
                    'INFO',
                    'WARNING',
                    'ERROR',
                    'ITEM_DUE',
                    name='notificationtype'),
                nullable=True))
        batch_op.add_column(
            sa.Column(
                'item_type',
                sa.Enum(
                    'NONE',
                    'TODO',
                    'CHORE',
                    'REMINDER',
                    name='itemtype'),
                nullable=True))
        batch_op.add_column(
            sa.Column(
                'item_id',
                sa.String(
                    length=100),
                nullable=True))
        batch_op.add_column(
            sa.Column(
                'is_removed',
                sa.Boolean(),
                nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('is_removed')
        batch_op.drop_column('item_id')
        batch_op.drop_column('item_type')
        batch_op.drop_column('notification_type')

    # ### end Alembic commands ###
