"""Add item_serialized column to history

Revision ID: 73b0a9c7bc69
Revises: 5a93e0a44d99
Create Date: 2025-08-04 16:05:17.572927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b0a9c7bc69'
down_revision = '5a93e0a44d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_serialized', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_column('item_serialized')

    # ### end Alembic commands ###
