"""Add push_subscription table

Revision ID: c1bd7aca9687
Revises: c20f50cd568c
Create Date: 2026-02-28 10:24:13.670309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1bd7aca9687'
down_revision = 'c20f50cd568c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscription',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh_key', sa.String(length=255), nullable=False),
    sa.Column('auth_key', sa.String(length=255), nullable=False),
    sa.Column('created_on', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('push_subscription')
    # ### end Alembic commands ###
