"""empty message

Revision ID: c20f50cd568c
Revises: 518f398b1bf5
Create Date: 2025-08-10 14:27:08.316219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20f50cd568c'
down_revision = '518f398b1bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iteration_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_iteration_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iteration_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_column('iteration_count')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('item_iteration_count')

    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.drop_column('iteration_count')

    # ### end Alembic commands ###
