name: Build linux/arm64 image and publish to Github registry
permissions:
  contents: read
  packages: write
on: [ workflow_dispatch ]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: docker/Dockerfile
        platforms: linux/arm64
        push: true
        tags: ghcr.io/jonasherzfeld/tidymate:dev
        cache-from: type=local,src=/tmp/.buildx-cache  # Reuse cached layers from previous builds.
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max  # Save new cache layers after the build.

    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache