name: BUild and publish docker image to Github
on:
    [workflow_dispatch]

jobs:
    publish_image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: 'Login to GitHub Container Registry'
                uses: docker/login-action@v1
                with:
                  registry: ghcr.io
                  username: ${{github.actor}}
                  password: ${{secrets.GITHUB_TOKEN}}

            - name: Build Docker image
              run: |
                docker build -t tidymate:latest -f docker/Dockerfile .

            - name: Push Docker image
              run: |
                docker push ghcr.io/${{github.actor}}/tidymate:latest
