name: Preview Deployment

on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/npm-install
      - name: Setup Turbo Cache
        uses: rharkor/caching-for-turbo@v1.5
        with:
          cache-prefix: tidymate_
      - name: Build
        run: npm run build
      - name: Prepare distribution
        run: mkdir -p ./dist/docs && cp -r ./packages/app/dist/* ./dist && cp -r ./packages/docs/out/* ./dist/docs
      - name: Cache workspace
        id: cache-tidymate
        uses: actions/cache@v4
        with:
          path: .
          key: ${{ runner.os }}-tidymate
  deploy:
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.details_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Restore cached workspace
        id: cache-tidymate
        uses: actions/cache/restore@v4
        with:
          path: .
          key: ${{ runner.os }}-tidymate
      - name: Extract branch name
        shell: bash
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" | tr / - >> $GITHUB_ENV
        id: extract_branch
      - name: Deploy to Firebase
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TIDY_MATE }}
          projectId: tidy-mate
          channelId: ${{ env.branch_name }}
