name: Deploy to Live Environment
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/npm-install
      - name: Setup Turbo Cache
        uses: rharkor/caching-for-turbo@v1.5
        with:
          cache-prefix: tidymate_
      - name: Build
        run: npm run build
      - name: Prepare distribution
        run: mkdir -p ./dist/docs && cp -r ./packages/app/dist/* ./dist && cp -r ./packages/docs/out/* ./dist/docs
      - name: Cache workspace
        id: cache-tidymate
        uses: actions/cache@v4
        with:
          path: .
          key: ${{ runner.os }}-tidymate
  deploy:
    environment:
      name: production
      url: ${{ steps.deploy.outputs.details_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Restore cached workspace
        id: cache-tidymate
        uses: actions/cache/restore@v4
        with:
          path: .
          key: ${{ runner.os }}-tidymate
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TIDY_MATE }}
          channelId: live
          projectId: tidy-mate
