name: Preview Deployment

on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/npm-install
      - name: Setup Turbo Cache
        uses: rharkor/caching-for-turbo@v1.5
        with:
          cache-prefix: tidymate_
      - name: Build
        run: npm run build
      - name: Upload App Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tidymate-app-artifact
          path: ./packages/app
  deploy:
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.details_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download App Artifact
        uses: actions/download-artifact@v3
        with:
          name: tidymate-app-artifact
      - name: Extract branch name
        shell: bash
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" | tr / - >> $GITHUB_ENV
        id: extract_branch
      - name: Deploy to Firebase
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TIDY_MATE }}
          projectId: tidy-mate
          channelId: ${{ env.branch_name }}
