name: Deploy to Live Environment
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: npm run build && npm run build:cp-public
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tidymate-artifact
          path: .
  deploy:
    environment: 
      name: production
      url: ${{ steps.deploy.outputs.details_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: tidymate-artifact
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TIDY_MATE }}
          channelId: live
          projectId: tidy-mate
