name: Deploy to Live Environment
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/npm-install
      - name: Build
        run: npm run build
      - name: Upload App Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tidymate-app-artifact
          path: ./packages/app/build
  deploy:
    environment:
      name: production
      url: ${{ steps.deploy.outputs.details_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download App Artifact
        uses: actions/download-artifact@v3
        with:
          name: tidymate-app-artifact
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TIDY_MATE }}
          channelId: live
          projectId: tidy-mate
